// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/leafney/whisky/config"
	"github.com/leafney/whisky/internal/api"
	"github.com/leafney/whisky/internal/biz"
	"github.com/leafney/whisky/internal/dao"
	"github.com/leafney/whisky/internal/service"
	"github.com/leafney/whisky/pkg/cronx"
	"github.com/leafney/whisky/pkg/leveldbx"
	"github.com/leafney/whisky/pkg/versionx"
	"github.com/leafney/whisky/pkg/xlogx"
)

// Injectors from wire.go:

func BuildInjector(stop chan struct{}) (*Injector, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	xLogSvc := xlogx.NewXLogSvc(configConfig)
	infoSvc := versionx.NewInfoSvc()
	home := &api.Home{
		VersionSvc: infoSvc,
	}
	router := &service.Router{
		XLog: xLogSvc,
	}
	levelDBSvc := leveldbx.NewLevelDBSvc(configConfig, xLogSvc, stop)
	monitor := &dao.Monitor{
		XLog:    xLogSvc,
		LevelDB: levelDBSvc,
	}
	bizMonitor := &biz.Monitor{
		XLog:       xLogSvc,
		Config:     configConfig,
		MonitorDao: monitor,
	}
	networkMonitor := &service.NetworkMonitor{
		XLog:       xLogSvc,
		MonitorBiz: bizMonitor,
	}
	cronSvc := cronx.NewCronSvc(configConfig, xLogSvc, stop)
	cron := &service.Cron{
		XLog:       xLogSvc,
		Config:     configConfig,
		CronSvc:    cronSvc,
		MonitorBiz: bizMonitor,
	}
	apiRouter := &api.Router{
		XLog:              xLogSvc,
		RouterSvc:         router,
		NetworkMonitorSvc: networkMonitor,
		CronSvc:           cron,
	}
	yAcd := &service.YAcd{
		XLog:    xLogSvc,
		LevelDB: levelDBSvc,
	}
	apiYAcd := &api.YAcd{
		XLog:    xLogSvc,
		YacdSvc: yAcd,
	}
	netWork := &service.NetWork{
		XLog: xLogSvc,
	}
	apiNetWork := &api.NetWork{
		NetWorkSvc: netWork,
	}
	sCrash := &service.SCrash{
		XLog: xLogSvc,
	}
	apiSCrash := &api.SCrash{
		XLog:      xLogSvc,
		SCrashSvc: sCrash,
	}
	cronTask := &api.CronTask{
		XLog:              xLogSvc,
		CronSvc:           cron,
		NetworkMonitorSvc: networkMonitor,
	}
	defRouter := DefRouter{
		HomeApi:           home,
		RouterApi:         apiRouter,
		YacdApi:           apiYAcd,
		NetWorkApi:        apiNetWork,
		SCrashApi:         apiSCrash,
		NetworkMonitorSvc: networkMonitor,
		CronSvc:           cron,
		CronTaskApi:       cronTask,
	}
	injector := &Injector{
		L: xLogSvc,
		R: defRouter,
		C: configConfig,
	}
	return injector, func() {
	}, nil
}
